import 'package:merchant_dashboard/utils/customer_data.dart';

List<CustomerData> customerDataList = [
  CustomerData(
    all: 'all',
    customerId: 1,
    date: 1023,
    hide: false,
    manage: 'View Details',
    name: 'Meta Corp',
    status: 'Active',
  ),
  CustomerData(
    all: 'all',
    customerId: 2,
    date: 1023,
    hide: true,
    manage: 'View Details',
    name: 'Jk Corp',
    status: 'Stopped',
  ),
  CustomerData(
    all: 'all',
    customerId: 3,
    date: 1023,
    hide: true,
    manage: 'View Details',
    name: 'Ketchup Corp',
    status: 'Active',
  ),
  CustomerData(
    all: 'all',
    customerId: 4,
    date: 1023,
    hide: false,
    manage: 'View Details',
    name: 'Harsha Corp',
    status: 'Invited',
  ),
  CustomerData(
    all: 'all',
    customerId: 5,
    date: 1023,
    hide: false,
    manage: 'View Details',
    name: 'Pavan Corp',
    status: 'Stopped',
  ),
  CustomerData(
    all: 'all',
    customerId: 6,
    date: 1023,
    hide: true,
    manage: 'View Details',
    name: 'Akshitha Corp',
    status: 'Active',
  ),
  CustomerData(
    all: 'all',
    customerId: 7,
    date: 1023,
    hide: true,
    manage: 'View Details',
    name: 'raju Corp',
    status: 'Active',
  ),
  CustomerData(
    all: 'all',
    customerId: 8,
    date: 1023,
    hide: true,
    manage: 'View Details',
    name: 'kalyan Corp',
    status: 'Active',
  ),
  CustomerData(
    all: 'all',
    customerId: 9,
    date: 1023,
    hide: true,
    manage: 'View Details',
    name: 'abhishek Corp',
    status: 'Active',
  ),
  CustomerData(
    all: 'all',
    customerId: 10,
    date: 1023,
    hide: true,
    manage: 'View Details',
    name: 'anjali Corp',
    status: 'Active',
  ),
  CustomerData(
    all: 'all',
    customerId: 11,
    date: 1023,
    hide: true,
    manage: 'View Details',
    name: 'Prakash Corp',
    status: 'Active',
  ),
];
